name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet 10.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: Clean
        run: dotnet clean Colosoft.Text.slnx -c Release

      - name: Build
        run: dotnet build Colosoft.Text.slnx -c Release

      - name: Build
        run: dotnet pack Colosoft.Text.slnx -c Release
        
      - name: Publish to Nuget.org
        run: dotnet nuget push ./output/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.colosoft.com.br/v2